name: Update Docker image

on:
  push:
    branch: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --tag mundy.io --label mundy.io

      - name: Login to registry
        run: echo ${{ secrets.ACCESS_TOKEN }} | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          docker tag mundy.io ghcr.io/ted-mundy/mundy.io:latest
          docker push ghcr.io/ted-mundy/mundy.io:latest